on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Lori_assignment project `Lori_assignment` CI on ECR

jobs:
  deploy:
    name: Deploying
    runs-on: ubuntu-latest
    steps:
    - name: Deploying Application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_AWS_SERVER_IP }}
        username: ${{ secrets.SSH_SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
           cd .script
           ls 
         
